### ISSUE TITLE
Request for `api.login_with_test_token(...)`

### ISSUE THREAD

**Issue by gwpl** [Doist/todoist-python#14]
I've created in https://developer.todoist.com/appconsole.html "Test Token". However I can not use it with todoist api as it only allows `api.login(email,password)` or `api.login_with_google(...)`.

Therefore feature request for `api.login_with_test_token(...)`.

**Comment by eleftherios-c** [comment]
You don't need to login with the test token; the test token works the same way as a regular access token. So you basically use it to access you account like this:

```python
import todoist
api = todoist.TodoistAPI('your-test-token-goes-here')
api.items.sync()
...
```
