### ISSUE TITLE
Get all tasks (items)

### ISSUE THREAD

**Issue by jaidevd** [Doist/todoist-python#22]
Would it help to have a method of the `todoistAPI` class which returns all completed and incomplete tasks? I have a simple implementation of this. If you like I can send a patch.

Thanks!

**Comment by lefcha** [comment]
I think that we don't provide this functionality on purpose, as we want our users to mainly focus on their active data, and also our Sync API is optimized working with this active data.

Some users have thousands of completed tasks and thus we want to avoid having users fetching those in an easy way.  But we also provide some way to retrieve archived projects or completed tasks (but only per project), as this is also needed some times, but it's the exception not the usual use case.

But anyway thanks for offering to provide some code for this, unfortunately for now we're not interested in having such functionality offered from our official Todoist module.

**Comment by jaidevd** [comment]
:+1:
