### ISSUE TITLE
Complete a recurring task not working

### ISSUE THREAD

**Issue by DongjunLee** [Doist/todoist-python#26]
```python
>>> import todoist
>>> api = todoist.TodoistAPI('0123456789abcdef0123456789abcdef01234567')
>>> api.items.update_date_complete(33548400, '2014-10-30T23:59', 'every day', 1)
>>> api.commit()
```

thie function is not working.
I need advice.

**Comment by PotHix** [comment]
Hi @DongjunLee,

Tried it in my local environment and it works. I used the same code but with my own data:

```
>>> import todoist
>>> api = todoist.TodoistAPI('xxxxMYTOKENxxxx')
>>> api.items.update_date_complete(2263491951,'2017-07-20T23:59','every day',1)
>>> api.commit()
{u'collaborators': [ ... a lot of info here... ]}
```

What information do you need about it?

**Comment by PotHix** [comment]
@DongjunLee I'm closing this issue since we did not receive a follow-up from you, please ask again in case you need help with our Python library. :)

**Comment by DongjunLee** [comment]
Hi @PotHix,

Sorry for late commet.

When I first created the issue, it was not
Now it is good

Thank you for your comment  :)
