### ISSUE TITLE
Doesn't work in Atom

### ISSUE THREAD

**Issue by RorixRebel** [Doist/todoist-python#27]
Somehow the package doesnt work in Atom.
works ok on ptpython and pycharm but for some reason using Atom causes weird issues.

```
pip list | grep todoist
todoist-python (7.0.17)

pip3 list | grep todoist
todoist-python (7.0.17)
```
Code:
```
import todoist

api = todoist.TodoistAPI('lalalalal')
data = api.sync()

print(data)
```

Error:

>  api = todoist.TodoistAPI('lalalalal')
> AttributeError: 'module' object has no attribute 'TodoistAPI'
> [Finished in 0.04s]

any clue?

**Comment by PotHix** [comment]
@RorixRebel not sure but the library doesn't depend or use anything that could make it happen. Do you have other Python packages working on you Atom environment?

**Comment by PotHix** [comment]
@RorixRebel installed fresh version Atom just to try it.

Installed `Scripts` package and used it to run my Python code, it works as expected.
Here is a screenshot of it:

![image](https://user-images.githubusercontent.com/14836/28341967-60b1fab6-6bec-11e7-8c2a-5a4fce7b82ba.png)

My task was changed as expected:

![image](https://user-images.githubusercontent.com/14836/28341996-829ff88a-6bec-11e7-96d2-29aa40b4c90c.png)

It's probably some configuration problem but we are not skilled enough with Atom to help you with that, hope you understand. :)

**Comment by RorixRebel** [comment]
it seems like the package i installed from pypi wasn't good.
downloaded what you have here and it works now.

thanks!
