### ISSUE TITLE
Allow library to call for partial sync

### ISSUE THREAD

**Issue by khurshid-alam** [Doist/todoist-python#28]
`result = api.sync(resource_types=['projects'])` doesn't work any more and returns 

> TypeError: sync() got an unexpected keyword argument 'resource_types'

Allow `resource types` to be set with `api.sync` so user can call partial sync.

**Comment by PotHix** [comment]
We decided to not use `resource_types` to avoid managing many types of caches and sync tokens locally. The `api.sync()` already deals with partial syncs by default, you just have to select the data you want to use.

**Comment by khurshid-alam** [comment]
Alright. Thanks.
