### ISSUE TITLE
How to get task modified time using this library?

### ISSUE THREAD

**Issue by khurshid-alam** [Doist/todoist-python#29]
Any idea how can I get task modified time with this library?

**Comment by PotHix** [comment]
Hi @khurshid-alam, 

Which API field are you mentioning? [Here](https://developer.todoist.com/sync/v7/) you can find all the fields we're currently exposing for the task (item).

**Comment by khurshid-alam** [comment]
@PotHix 

Hmmm...it seems Todoist doesn't save item modified time at all. The only work around I found with activity.get method, but even that doesn't work as expected...




```python
import todoist
from pprint import pprint

api = todoist.TodoistAPI("455************", cache="/home/pcuser/.cache/todoist")
pprint(api.activity.get(object_event_types=["item:added", "item:updated"])) #this doesn't work
pprint(api.activity.get(object_type="item", event_type="updated")) #this works though
```
Any idea why?

**Comment by PotHix** [comment]
Hi @khurshid-alam,

`object_event_types` expects a JSON value. This will work as expected:

```
import todoist
from pprint import pprint

api = todoist.TodoistAPI(token)
pprint(api.activity.get(object_event_types='["item:added", "item:updated"]'))
```

We will implement an auto conversion to JSON in case we receive a Python object, so we will avoid problems like this in the future. :)

**Comment by khurshid-alam** [comment]
Yes it works. Thanks.

**Comment by dmitrij-drandarov** [comment]
Does not seem to be implemented yet.
The documentation doesn't make that very clear:
![image](https://user-images.githubusercontent.com/13102251/78056772-ee0e9880-7385-11ea-97c5-be137d63cfb2.png)
