### ISSUE TITLE
Request for packaging for Debian

### ISSUE THREAD

**Issue by khurshid-alam** [Doist/todoist-python#31]
I would love to have todoist library available at debian. So that can be installed using apt.

`sudo apt-get install python3-todoist`.

since ubuntu sync with debian it will be automatically available in ubuntu.

As per debian norm binary package name must be in form of python{3}-package.  For example:

1) python-todoist (for python2 compatibility)
2) python3-todoist (for python3 compatibility)

Source package name can be same (todoist-python). see below debian folder for example.

As a starting point you can look into: https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html

To make package available in you must file an [ITP (intent to package)](https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html#itp). You can see dropbox example here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828940

To make things easier I have created a ppa in Ubuntu. You can look at source and the content of debian folder here: https://github.com/khurshid-alam/todoist-debian/tree/master/debian

As of now I am maintaining the ppa for Ubuntu. But this should officially be available in debian. 

Please let me know what you think. I can help you to package todoist in debian/Ubuntu.

Thanks.

**Comment by PotHix** [comment]
Hi @khurshid-alam,

After some discussion about this topic, we decided to not put effort on this matter.
Thanks for your suggestion. :)

**Comment by khurshid-alam** [comment]
Alright. Thanks.
