### ISSUE TITLE
reminders.get_by_id always returns None

### ISSUE THREAD

**Issue by GregSal** [Doist/todoist-python#34]
import todoist as tdi
api = tdi.TodoistAPI(token)
project = api.projects.add('test1')
api.commit()
item = api.items.add('Task1wReminder', project['id'])
api.commit()
reminder = api.reminders.add(item['id'], service='email', due_date_utc='2017-11-20T11:00')
api.commit()
retrieved_reminders = api.reminders.get_by_id(item['id'])
print(retrieved_reminders)

returns None

**Comment by PotHix** [comment]
@GregSal you should use the reminder id instead of the item id. 

```
retrieved_reminders = api.reminders.get_by_id(reminder['id'])
```

Just tried and it works as expected
