### ISSUE TITLE
Collaborators not persisted/available 

### ISSUE THREAD

**Issue by seliger** [Doist/todoist-python#35]
The collaborators dictionary is empty when using the Python API. After spending time digging through HTTPS dumps and seeing collaborators in the stream, I did some more digging in the library. There appears to be an issue with the api.py file on this line:

```python
resp_models_mapping = [
    ('collaborator', models.Collaborator),
    ('collaborator_states', models.CollaboratorState),
    ('filters', models.Filter),
    ('items', models.Item),
    ('labels', models.Label),
    ('live_notifications', models.LiveNotification),
    ('notes', models.Note),
    ('project_notes', models.ProjectNote),
    ('projects', models.Project),
    ('reminders', models.Reminder),
]
```

Note that it says "collaborator" and not "collaborators". I changed it to collaborators and am now able to access the values.

I will be submitting a pull request (#36 ) with the fix. I tried running the test scripts, but many parts fail for my test accounts since they are not premium (and I don't want to run test scripts against my real Todoist premium account).

**Comment by PotHix** [comment]
The fix mentioned in #36 was released.
