### ISSUE TITLE
Query method not documented anywhere

### ISSUE THREAD

**Issue by RorixRebel** [Doist/todoist-python#37]
Found the query method which solves 90% of what im trying to do (get a tasks that i have due for today) somewhere in the todoistapi model.
Can this be properly documented?

The queries argument, what does it take?
what is an acceptable parameter?

```
def query(self, queries, **kwargs):
        """
        Performs date queries and other searches, and returns the results.
        """
        params = {'queries': json_dumps(queries),
                  'token': self.token}
        params.update(kwargs)
        return self._get('query', params=params)
```

tried giving it something like "TODAY"
and i get one result per letter which is not ideal.

while playing in postman i see it hits this endpoint - https://todoist.com/API/v7/query
and it takes the token and queries but again, what is acceptable in queries?

**Comment by PotHix** [comment]
Hi @RorixRebel,

The `query` is an old and deprecated endpoint. It's not fully working and this is the reason we don't have a documentation for that and encourage to not use it anymore (another answer about it [here](https://github.com/Doist/todoist-api/issues/22)).

We know it's important to have filters and we are currently experimenting with them in our [REST API](https://developer.todoist.com/rest/v8/#get-tasks), but it's still beta. For the sync API, we recommend filtering in the client.

The `query` method will be removed, thanks for reporting.
