### ISSUE TITLE
Share a project: "message" is defined but never used

### ISSUE THREAD

**Issue by Cosmitar** [Doist/todoist-python#42]
I found this. Seems to be an unused parameter in **share** method into manager for Projects.
https://github.com/Doist/todoist-python/blob/master/todoist/managers/projects.py#L97

**Comment by imankulov** [comment]
Can confirm that. We used to use "message" argument in older versions of the API, and they generated personal message to invitees. At some point we decided to exclude it (and now there is no way to send a personal invitation message to recipients), but we kept the attribute in Python code to keep backward compatibility for older versions.

I think we can safely deprecate this in the newer version. Thanks for the notification!

**Comment by PotHix** [comment]
It was removed during the refactor to implement the v8 API. Sorry for not closing it earlier.
