### ISSUE TITLE
README example is potentially misleading

### ISSUE THREAD

**Issue by ErikBoesen** [Doist/todoist-python#47]
The README suggests passing no parameters to the `TodoistAPI` constructor, and then using `TodoistAPI.user.login()` to sign in the user. It seems from my experimentation that a simpler signin solution is to simply pass the Todoist token to the `TodoistAPI` constructor. Am I correct in this assumption?

If so I'm definitely happy to modify the README myself, so you guys don't have to bother.

Thanks either way for creating a great API wrapper for a great app!

**Comment by PaulHalliday** [comment]
Erik,

Thanks for your feedback. I've changed this to use the `todoist.TodoistAPI('api-token')` syntax. 👍
