### ISSUE TITLE
Read-only file system error on Google App Engine

### ISSUE THREAD

**Issue by drmauij** [Doist/todoist-python#48]
Trying to use Sync API on Google App Engine with:
`api = todoist.TodoistAPI(myAccessToken)`
and getting a "Read-only file system error".

Does it mean I can only use REST Api or is there any workaround?

**Comment by mursts** [comment]
Hi @drmauij 

Please try `api = todoist.TodoistAPI(myAccessToken, cache=False)` or you should use Python 3.7 runtime (beta)

```
First generation Python 2.7 runtime does not allow native code, filesystem access, or arbitrary network connections, and has proprietary APIs.
```
https://cloud.google.com/appengine/docs/python/?hl=ja

**Comment by PotHix** [comment]
@mursts probably solved this problem long ago. Will close this one.
