### ISSUE TITLE
Make it possible to delete or update items by id

### ISSUE THREAD

**Issue by imankulov** [Doist/todoist-python#5]
Currently, if I want to delete a task, I have to do something like this:

    >>> task = api.items.get_by_id(123)
    >>> task.delete()

Same with the update, and other operations. It's not always convenient, when we don't have a synchronized client-side state, don't want to perform the full sync operation, just know the object id, and want to delete or update it. Something like this:

    >>> api.items.delete(id=123)
    # id to lookup, everything else to update
    >>> api.items.update(id=123, content='foo')

Needed for the PowerApp at this point :)

**Comment by eleftherios-c** [comment]
Closed by 71ba6c31cdb1a200ea14a1b160c54618e56f9afa.

**Comment by imankulov** [comment]
Thanks for the update, @eleftherios-c  yet it seems it's not working in the PowerApp environment. The problem is that in Powerapp there are so-called "stateless integrations" and it's explicitly forbidden for them to call `get_by_id` and friends (as they're stateless, we don't want them to perform full sync "accidentally").

Your implementation of manager commands perform `get_by_id` in almost every method, and it breaks the logic of them (they die with exceptions).

What I actually wanted to have is a thin wrapper around our Sync commands. To make it more clear, I show you my examples:

- [Subclass of stateless API clients](https://github.com/Doist/powerapp/blob/master/powerapp/core/sync.py#L86-L99)
- [That's how it's used](https://github.com/Doist/powerapp/blob/master/powerapp/sync_bridge/todoist_sync_adapter.py#L39)

And finally, as an example, that's how I implemented my own local stub of `api.items.delete()`


    def delete(self, item_id):
        """
        Deletes item, and appends the equivalent request to the queue.
        """
        item = {
            'type': 'item_delete',
            'uuid': self.api.generate_uuid(),
            'args': {
                'ids': [item_id],
            },
        }
        self.api.queue.append(item)
        # TODO: we need a better and more generic approach
        # self.api.state['Items'].remove()

Hopefully, you can fix it soon. Thanks!

**Comment by imankulov** [comment]
Status update. The issue is note very pressing, as I added "stateless commands" directly to my "stateless subclass": https://github.com/Doist/powerapp/commit/0736fa264b274ad471efd25c864ac429d48495b1

**Comment by eleftherios-c** [comment]
Now managers are not changing the local state, and just work remotely
and only append requests to the queue (thus they are suited for
applications that want a more stateless approach).

Also, the models' instances (objects) are using the aforementioned
managers to append requests to the queue, and additionally they are
modifying themselves, too.

And by having the objects reuse the managers functions, we avoid
having similar code twice (the appending of requests to the queue part).

**Comment by eleftherios-c** [comment]
Closed by 197aad1af7a5f11237fbc027fbdef03330bb0b58.
