### ISSUE TITLE
Dates added and due being incorrectly set

### ISSUE THREAD

**Issue by ccarterlandis** [Doist/todoist-python#54]
I'm not sure if this is a timezone issue or not, but I've got my timezone set to America/Chicago (UTC -6:00), which is the correct timezone for where I am. 

When I add a new task, not only is the `date added` field exactly 8 hours ahead of where it should be (e.g. if I add a task at 11:33:35 my time on Monday, February 11, the `date_added` field in the Sync response will have a value of `Mon 11 Feb 2019 17:33:35 +0000`).

The `due_date_utc` is almost 6 hours ahead, but not quite? I'm not sure how tasks with due dates but not times are handled in the system, but if I add a task to be due on 2/11 with no time specified, then in the Sync response the `due_date_utc` field will have a value of `Tue 12 Feb 2019 05:59:59 +0000`, which is just not right.

This problem **just** started occuring, without me changing any of my settings at all.

Versions:
macOS Mojave: v10.14.2
Python: v3.6.3
todoist-python library: v7.0.19

**Comment by lefcha** [comment]
Is this still a problem with the latest 8.0.2 version?

**Comment by PotHix** [comment]
Closing as we didn't hear back from @ccarterlandis. Please reopen if you are still facing this issue and sorry for taking so long to reply.
