### ISSUE TITLE
Adding sub-task (indented task) to existing task

### ISSUE THREAD

**Issue by kbakk** [Doist/todoist-python#56]
How can I create a sub-task, given I have an existing task?

In https://github.com/Doist/todoist-python/issues/24#issuecomment-301053036 lefcha mentions:

> The current way of figure out the tasks and sub-tasks hierarchy is by using the `item_order` and `indent` properties of item objects inside each project. The first orders the items from `1`, `2`, and up to the last, while the `indent` adds indentation to a task to make it a sub-task of the task that is above it and has a lower `indent` level.
> [...]
> ```
> - A (1, 1)
> - B (2, 1)
>   - C (3, 2)
>     - D (4, 3)
>   - E (5, 2)
> -F (6, 1)
> ```

In order to create a sub-task for A in above example, would I need to increase `item_order` on all other tasks first, then create my A-subtask as `item_order=2, indent=2`? 

Or is there an easier way?

**Comment by 6uhrmittag** [comment]
This was explained in a recent commit: https://github.com/Doist/todoist-python/commit/29864f6b390f64b560fad891fdb9d3c26ca5237f

> * The `item_order` and `indent` properties of projects, that denoted a visual
  hierarchy for the projects (the order of all the projects and the level of
  indent of each one of them), were replaced by `parent_id` and `child_order`,
  which denote a real hierarchy (the parent project of a project and the order
  of all children of a specific parent project).

So, `indent ` is finally deprecated in favor of  `parent_id` and `child_order`.

I didn't tried it myself, but i use the `parent_id` to find all subtasks of a task list in [taskbutler](https://github.com/6uhrmittag/taskbutler), so it probably works as expected.

**Comment by PotHix** [comment]
@6uhrmittag is right, `indent` will be removed along with the version 7 of the API and `parent_id` is the way to go :+1:
