### ISSUE TITLE
Undocumented API endpoint

### ISSUE THREAD

**Issue by scholer** [Doist/todoist-python#60]
The [migration guide for v8 Sync API](https://developer.todoist.com/sync/v8/#migration-guide) states that:

> The URL changed from `https://todoist.com/api/v7/*` to `https://api.todoist.com/sync/v8/*`

However, the current `todoist.api` module effectively uses `https://todoist.com/api/v8/*`, c.f. [line 56](https://github.com/Doist/todoist-python/blob/master/todoist/api.py#L56) and  [line 128](https://github.com/Doist/todoist-python/blob/master/todoist/api.py#128):

```python
    def __init__(self,
                 token='',
                 api_endpoint='https://todoist.com',
                 session=None,
                 cache='~/.todoist-sync/'):
        self.api_endpoint = api_endpoint
(...)

    def get_api_url(self):
        return '%s/API/v8/' % self.api_endpoint

```

In order to make this package consistent with the information in the API docs, I'd recommend changing the two lines, so the effective endpoint is `https://api.todoist.com/sync/v8/`. (Also, while you are at it, please make `TodoistAPI.api_endpoint` be the *actual* API end point, and not just the todoist domain name?)

**Comment by bnhgit** [comment]
is the below api response a symptom of this?

```
bash-5.0# python
Python 3.7.4 (default, Aug 12 2019, 21:20:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from todoist.api import TodoistAPI
>>> TODOIST_TOKEN = '<insertedmytokenhere>'
>>> api = TodoistAPI(TODOIST_TOKEN)
>>> api.sync()
'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>410 Gone</title>\n<h1>Gone</h1>\n<p>This API endpoint is no longer available. Please refer to our documentation to upgrade your client to use the latest API version: https://developer.todoist.com</p>\n'
>>> 
```

**Comment by scholer** [comment]
No, the error you are getting is because you are using an outdated version of `todoist-python` package, at least 9 months old, which still uses the old v7 API end point. You should be able to simply update via `pip install -U todoist-python`, and you should see the error message disappear.

However, since the current `todoist-python` version uses `https://todoist.com/api/v8/*`, which is not technically the correct URL, I'd expect we could easily have a situation where even the current version doesn't work, because someone decided to disable `https://todoist.com/api/v8/*` (because the API entry points are now hosted at **api**.todoist.com).

**Comment by lefcha** [comment]
Fixed by https://github.com/Doist/todoist-python/commit/20ee6e44ea32526313f17106f075832b3b4a60fa.

**Comment by lefcha** [comment]
Thanks for reporting @scholer !
