### ISSUE TITLE
Item.update_date_complete() raises TypeError

### ISSUE THREAD

**Issue by scholer** [Doist/todoist-python#61]
The signature of `ItemsManager.update_date_complete()` is: `def update_date_complete(self, item_id, due=None)`.  ([todoist.managers.items, line 151](https://github.com/Doist/todoist-python/blob/master/todoist/managers/items.py#L151))

However, this itemsmanager method is called from `Item.update_date_complete()` with: `self.api.items.update_date_complete(self['id'], new_date_utc, date_string, is_forward)`.  ([todoist.models, line 132](https://github.com/Doist/todoist-python/blob/master/todoist/models.py#L132))

Clearly, the number of arguments don't match: `ItemsManager.update_date_complete()` only accepts two arguments (`item_id` and `due`), but `Item.update_date_complete()` attempts to call the `ItemsManager` method with four arguments, raising a `TypeError`.

**Comment by lefcha** [comment]
You're right this wasn't updated properly during the `v7->v8` migration.  Thanks for reporting!

**Comment by lefcha** [comment]
Fixed by https://github.com/Doist/todoist-python/commit/aae7b37364ceaca60e593db84f48d0eac6f89e49.
