### ISSUE TITLE
Calling "in" on Module class exits with KeyError

### ISSUE THREAD

**Issue by 5t4cktr4c3** [Doist/todoist-python#64]
Calling `in` on Module class objects (for example Items) will cause an KeyError, see attached example for further information. Checking that the API-reply contains items with `id`-property might be not necessary, but important to make sure that the processing succeeds.

Python console output
> Traceback (most recent call last):
>   File "/Users/path/to/file.py", line 11, in <module>
>     print("id" in applicationInterface.state["items"][0])
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/todoist/models.py", line 16, in __getitem__
>     return self.data[key]
> KeyError: 0
> 
> Process finished with exit code 1

Code example
```
api = TodoistAPI(token)
api.sync()
print("id" in api.state["items"][0]) # checking the existence of id-property: expecting a boolean
```

**Comment by nmusolino** [comment]
For an explanation of why this is happening, see this StackOverflow question:
https://stackoverflow.com/questions/58580574/in-keywoard-causes-keyerror-with-todoist-api/58580596#58580596

In short, Python is falling back to the sequence protocol (which calls `Model.__getitem__`) to evaluate `"id" in item`.  

The `Model` class should provide `__contains__` in addition to `__getitem__`.  For background, see the [Python data model page](https://docs.python.org/3/reference/datamodel.html#emulating-container-types).

> It is recommended that both mappings and sequences implement the __contains__() method to allow efficient use of the in operator; for mappings, in should search the mapping’s keys; for sequences, it should search through the values:
> [...]
> The membership test operators (in and not in) are normally implemented as an iteration through a sequence. However, container objects can supply the following special method with a more efficient implementation, which also does not require the object be a sequence.

**Comment by 5t4cktr4c3** [comment]
Adding the following code to `models.py` fixes the issue:
```python
def __contains__(self, value): # own/unofficial implementation
    return value in self.data
```

**Comment by lefcha** [comment]
You're right @5t4cktr4c3 and @nmusolino! Thanks for the fix, too.

**Comment by lefcha** [comment]
Closed by https://github.com/Doist/todoist-python/commit/6ae440252b305175e95ffaaa828b146faa78cecb.
