### ISSUE TITLE
Getting All Tasks

### ISSUE THREAD

**Issue by yrizk** [Doist/todoist-python#74]
Hi, 
I would like to know how it is possible to get ALL tasks for a user using these api? All the methods that sound like they would do this only return "active" items, and only go back 1 week or so. I would like to use my own data to build some visualizations. 
I read a previous conversation about this[1], but I would really like to get all my own data. frankly even though there are alot of them, I don't see why that shouldn't be exposed in some way. As a premium user its a little weird (maybe even GDPR incompliant but I'm not a lawyer) that I can't download all my data off your servers.

Thank you. 

[1] https://github.com/Doist/todoist-python/issues/22

**Comment by lb28** [comment]
I would like to download my data in order to play around with it (e.g. show a graph of my avg. activity).
I feel like there should be some way of accessing all tasks, or just all completed tasks, that are stored on Todoist's servers.

**Comment by 6uhrmittag** [comment]
There is no way to get all tasks at once, but it should be possible to get them by using the sync API:

- https://developer.todoist.com/sync/v8/#get-all-projects
- https://developer.todoist.com/sync/v8/#get-all-completed-items


Here you get all items. They do include _not hidden but completed_ items though, so items with `completed: 1` must be filtered
````
curl https://api.todoist.com/sync/v8/sync -d token=TOKEN -d sync_token=* -d resource_types='["items"]'
````
The `get_all` returns maximum 200 items, you can use `offset` to get all of them eventually:
````
curl https://api.todoist.com/sync/v8/completed/get_all     -d token=TOKEN-d limit=200
curl https://api.todoist.com/sync/v8/completed/get_all     -d token=TOKEN-d limit=200 -d offset=200
````
(you could get the total number of _completed_ via `/completed/get_stats`)


The Python SDK does include `api.completed.get_all()`, I'm just too much of a noob to figure out how to pass a `limit`. `get_all(limit=20)` doesn't work...

**Comment by 6uhrmittag** [comment]
To correct my above statement: it is super simple to use `api.completed.get_all` with the Python SDK.
Combine this with `api.state['items]`(+ exclude _is_deleted_, _is_archived_ and _in_history_ to remove duplicates) and you got all tasks.

````
    completed = api.completed.get_stats()['completed_count']

    print("page till fetched all " + str(completed) + " items")

    offset_fetch = 0
    while i <= offset_fetch:
        for item in api.completed.get_all(limit=200, offset=offset_fetch)['items']:
            print(item)
            i = i+1
        offset_fetch = offset_fetch + 200
    print("Done! Fetched " + i + " items")

````

Be carefull with the request-limit. I just hit the rate-limit(sorry!:D). So better add a few sleeps. ([doc: limits](https://developer.todoist.com/sync/v8/?python#limits))

**Comment by PotHix** [comment]
Thanks for your reply here @6uhrmittag! The best way to do this is indeed by using the `completed` API endpoint.

The Sync API returns all the active tasks. By doing that, the API does not send a lot of data when any client (android, iOS, web, integrations, etc) are syncing for the first time.

I'm closing this issue. :+1:
