### ISSUE TITLE
Timeblocking available?

### ISSUE THREAD

**Issue by datatalking** [Doist/todoist-python#76]
Is there functionality for setting up recurring or single event time-blocking within the API?

This is more likely an enhancement but I didn't see it in the Docs.

**Comment by datatalking** [comment]
As an update, would the todoist-python api be compatible with this?

I would it to access ical like this.

for time in ical:
     if time != scheduled >= 60 min
          fill_calendar = str(input("You have an open block of time, lets fill it")

**Comment by PotHix** [comment]
`todoist-python` doesn't support such a feature, neither our API. There's no concept of duration for a task in Todoist.
If you like to suggest a feature request, please do so via support: https://todoist.com/contact

I'm closing this issue :+1:
