### ISSUE TITLE
Example on main page

### ISSUE THREAD

**Issue by vit1251** [Doist/todoist-python#8]
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    api.ping('mytoken')
AttributeError: 'TodoistAPI' object has no attribute 'ping'

**Comment by Garee** [comment]
Thanks for reporting this issue. The `ping()` method was removed in a previous commit and we forgot to update the example.

I've created a pull request with an updated example: https://github.com/Doist/todoist-python/pull/9

**Comment by eleftherios-c** [comment]
Closed by e40b7117b751d8b2fc0629710b15a6b8d626961c.
