### ISSUE TITLE
Project_id not returned on items in state after sync

### ISSUE THREAD

**Issue by ashipper** [Doist/todoist-python#86]
Hi,

This looks to be a problem with the server not supplying the project_id.    Happy to raise directly in app.

**Comment by PotHix** [comment]
Can you please provide the steps to reproduce?

**Comment by ashipper** [comment]
running now returns project_id as expected

from todoist.api import TodoistAPI as api
api = TodoistAPI('d49d62564e47a21c439040d37e1dc41b05c1c7ce')
api.sync()
api.state['items']
