### ISSUE TITLE
Support for date parsing / scheduling using NLP

### ISSUE THREAD

**Issue by subash774** [Doist/todoist-python#87]
Todoist api for adding tasks doesn't support natural language processing for adding tasks and scheduling them like it does with the mobile app. Is it possible to do this with API call? 

"do this tomorrow" would schedule the task for tomorrow on the app but not with an API call.

**Comment by PotHix** [comment]
It doesn't seem to be related to the python library, so I'm closing this one.

Regarding the API, you probably want to use [the quick add API](https://developer.todoist.com/sync/v8/#quick-add-task)
