### ISSUE TITLE
Rate limiting when using completed.get_stats

### ISSUE THREAD

**Issue by joshsharp** [Doist/todoist-python#88]
Hi,

Apologies if this is the wrong spot for this issue, I couldn't find another public point of contact for your API.

When using `completed.get_stats()` I am getting what I assume are `HTTP 429 Too Many Requests` responses. I can only assume because this method only returns the body, not the headers or status code, and the body is a string of `Too Many Requests`.

The issue I have is that this rate limiting does not match the docs. [The docs state](https://developer.todoist.com/sync/v8/?python#limits):

> There’s also a maximum number of 50 sync requests per minute for each user.

I am only making one request per authenticated user within a large period (an hour or more), to `get_stats`, so I don't understand how I'm getting rate limited. If there are other limits on the API, can you please detail them? I assume there are hidden limits per client, rather than per user, otherwise I wouldn't be running into this.

Thanks!

**Comment by PotHix** [comment]
Hi @joshsharp! The best way to get support for the API is via [Todoist support](https://get.todoist.help/hc/en-us) and "Contact us". This way we can loop all the involved teams to find the solution. This repository is just for issues related to our Python library. 

I'm going to close this. :+1: 

_PS: I'm also an exist.io user. Love the product. :)_
