### ISSUE TITLE
Completed items showing as not completed in API data

### ISSUE THREAD

**Issue by sanmiguel** [Doist/todoist-python#89]
Hello there. I'm writing a small script that uses this library to access my Todoist data.

When working through some functionality to list certain items, I found quite a lot of the Items returned show no signs of being completed, but are definitely completed in the UI.

Perhaps I simply don't yet understand how to tell if an Item is `complete` in the API but here's what I had (directly under a top-level project, no sections or nested projects):

 - [x] Parent task
   - [x] Sub-task 1
   - [x] Sub-task 2
   - [x] Sub-task 3
      - [x] Sub-Subtask 1
      - [x] Sub-Subtask 2

All were shown as `complete` in the UI, but in the API all tasks had:
```
'checked': 0,
'date_completed': None,
'in_history': 0,
'is_deleted': 0
```

These were completed a few weeks ago via the UI (no idea if macOS, android or iOS, I use all 3), and the API was only sync'd this morning.

I then
 - 1: un-checked each of: `Sub-Subtask 1`, `Sub-task 3` and `Parent task` in the UI
 - 2: ran `api.sync()`
 - 3: checked each of the same
 - 4: ran `api.sync()`

The first sync received the changed tasks, as not completed (so effectively no change). When I then completed them in the UI and re-synced, they were received as updates and correctly showed as each having
```
'checked': 1,
'date_completed': '2020-11-03T10:42:55Z',
'in_history': 1,
'is_deleted': 1
```

Where am I going wrong?

**Comment by PotHix** [comment]
@sanmiguel can you please share a snippet of code that reproduces this issue?

**Comment by sanmiguel** [comment]
@PotHix sure - all I did was this:
```python
from todoist import APIState
api = APIState(token)

items = api.state['items']
```

The rest was just done by filtering that `items` list with list comprehensions. I haven't done an _exhaustive_ search of every task in my account, but I found at least a few more than the (obviously obfuscated) example I gave above - where the status of tasks in the `items` list didn't match what's shown in the UI.

**Comment by sanmiguel** [comment]
In case it's useful to know, I'm on version `todoist-python     8.1.2` and `python 3.8.3`

**Comment by PotHix** [comment]
I can't reproduce using the code shared. I just did a one-liner here to make things easy to check and reproduce:

```
rm -rf ~/.todoist-sync/ && python -c "import todoist; import os; token = os.environ.get('token'); api = todoist.TodoistAPI(token); [print(c['content']) for c in api.sync()['items']]"
```

This does a full-sync using my token available via environment variable `token` and prints the content of all tasks. I saw no problems there.

**Comment by sanmiguel** [comment]
@PotHix thanks for looking into this. The problem is I don't know _how_ to trigger this. The one thing in your steps I did not do was `rm -rf `/.todoist-sync/` so maybe I somehow had stale data in there but the first thing I always do is call `api.sync()` and then access items via `api.state['items']`. Is it possible that accessing it this way could result in seeing stale data?

**Comment by silentjay** [comment]
@sanmiguel No idea if this will help your issue but have you tried disabling the cache?

`api = todoist.TodoistAPI(myAccessToken, cache=False)`

**Comment by sanmiguel** [comment]
Thanks for the tip @silentjay I'll try that too.

Thinking more about how I hit this, the full actual flow must have been something like this:

 1. Create tasks via web UI/iOS app
  [several days later]
 2. Sync data to script via python `api.sync()`
  [several hours later]
 3. Complete tasks via web UI/iOS app
  [several hours later]
 4. Sync data to script via python `api.sync()`

Even after several syncs after step 4, I still was seeing those tasks as incomplete. It was only when I marked them as incomplete on the web UI, then completed them again, that they showed up as complete after an `api.sync()`.

Logically, they must have been cached locally - I guess just that cache doesn't work the way I thought it does and missed some updates along the way.

In future I'll just delete that cache and re-sync if I notice this again.

I'll close this now, and re-open later if I hit it again.
Thanks for you help, folks!
