### ISSUE TITLE
Unable to Find Basic Information in Todoist API Documentation

### ISSUE THREAD

**Issue by LloydThinks** [Doist/todoist-python#92]
Hi!

I am unable to find out how to get all items under a project ID. I'm not sure why this is not the first explained under https://developer.todoist.com/sync/v8/?python#items. Without this knowledge, how am I suppose to update or delete anything? I need the items (IDs) first.

Let me know if I have overlooked something in your API documentation.

Lloyd

**Comment by PotHix** [comment]
This client is based on the sync API, so you have to refer to the Sync method: https://developer.todoist.com/sync/v8/?python#sync
This method brings all the active information at once.

If you want something directly, we suggest you using the [REST API](https://developer.todoist.com/rest/v1/#tasks), but there's no client there.
