### ISSUE TITLE
about license

### ISSUE THREAD

**Issue by lanfon72** [Doist/todoist-python#96]
Hi there,

I just saw that `setup.py` declare the license is __BSD__,
https://github.com/Doist/todoist-python/blob/b9dd839b2b5287ba31416ef4e3746dc46bd812c2/setup.py#L20
and the `LICENSE` file wrote as __MIT__.
https://github.com/Doist/todoist-python/blob/b9dd839b2b5287ba31416ef4e3746dc46bd812c2/LICENSE#L1

Does it means that _todoist/_ is BSD and others are MIT?

**Comment by PotHix** [comment]
Thanks for pointing this out. It should be MIT everywhere (like [other](https://github.com/Doist/reactist) [projects](https://github.com/Doist/react-router-dom) we open sourced). I just changed the `setup.py` to reflect that.
